---
title: "flexspan example"
subtitle: Pandoc/Quarto extension
author: 
  - name: Georgios Pappas Jr
    affiliation:
      - name: University of Brasilia (UnB) - Brazil
filters:
  - _extensions/flexspan/flexspan.lua
flexspan:
  - left: "[-"
    right: "-]"
    command: "texttt" # Mono font in LaTeX 
  - left: "!!"
    right: "!!"
    command: "textbf" # Bold font in LaTeX
  - left: "--"
    right: "--"
    command: "custombox" # New command with an optional parameter that defines the color for drawing a box around the text. Default is Red
  - left: "-!"
    right: "!-"
    command: "custombox" 
    opts: Cerulean 

format:
  pdf:
    include-in-header:
      - text: |
          \usepackage[dvipsnames]{xcolor}
          \newcommand{\custombox}[2][Dandelion]{\colorbox{#1}{#2}}
    keep-tex: true
---

## Usage

This filter adds formatting to text by marking it with user-defined placeholders, before (left) or after (right) the text itself.

The placeholders should be defined in the extension metadata starting with the key `flexspan`. 

For the metadata definition: 

```markdown
flexspan:
  - left: "[-"
    right: "-]"
    command: "texttt" # Mono font in LaTeX 
  - left: "!!"
    right: "!!"
    command: "textbf" # Bold font in LaTeX
```

We can write the following paragraph 

```markdown
This is a test of [-flexspan-] extension and it is !!nice!!
```

The result is:

This is a test of [-flexspan-] extension and it is !!nice!!

The LaTeX code generated is: 

```latex
This is a test of \texttt{flexspan} extension and it is \textbf{nice}
```

### Options

The user can define [new commands in LaTeX](https://www.overleaf.com/learn/latex/Commands#Commands_with_optional_parameters), that should accept exactly two parameters: one optional (inside []) and one mandatory (inside {})

```latex
\renewcommand\custombox[2][Dandelion]{\colorbox{#1}{#2}}
```

Here, `custombox` was defined in the document metadata (`include-in-header`: see [PDF Basics – Quarto](https://quarto.org/docs/output-formats/pdf-basics.html#latex-includes)) and in the extension metadata, adding new placeholders to use this command. For example:

* Metadata

```markdown
flexspan:
  - left: "--"
    right: "--"
    command: "custombox" 
```

* Usage

```markdown
Using the new placeholders --flexspan-- 
```

* Rendered 

Using the new placeholders --flexspan-- 

### Passing options to the command 

Given that the `custombox` command accepts one optional argument, which is the name of the background color, we can pass it to the placeholders, enclosing it in parenthesis, after the right placeholder. 

* Usage

```markdown
Using the new placeholders --flexspan--(LimeGreen) with options
```

* Rendered 

Using the new placeholders --flexspan--(LimeGreen) with options
 
### Adding options to the metadata

Instead of passing options inside parenthesis, you can provide them in the metadata

* Metadata

```markdown
flexspan:
  - left: "-!"
    right: "!-"
    command: "custombox" 
    opts: Cerulean 
```

* Usage

```markdown
Using the new placeholders -!flexspan!- with opts: Cerulean
```

* Rendered

Using the new placeholders -!flexspan!- with opts: Cerulean


::: {.callout-note}

You can still pass options to a placeholder that contains default opts. In this case it will override the defaults 

* Usage

```markdown
Text -!flexspan!-(Salmon)
```

* Rendered

Text -!flexspan!-(Salmon)

:::

## WARNING 

1. Some placeholders are used by markdown and may not work, because they change the context of pandoc elements in the parse tree. For instance `left: [[` and `right: ]]` will be interpreted as and URL, and you should avoid using them. 

  * In case of a set of placeholders do not work, try changing them.

2. For instance, the placeholders `##` will **not** work when present in the first column of a paragraph, because it will be interpreted as a _Header 2_ element by the markdown parser.

  * However, `##text##` (without a space after ##) would work

## Rendering 

    quarto render example.qmd --to pdf
